// Bernal map sprites (M2). The two physical Bernal figures, each pre-rendered
// from a 3D model (three.js) to a player-colour PNG, then loaded + cached as an
// <Image> for the canvas renderer the same way the factory-base PNGs are:
//
//   - KALPANA  : two ribbed cones pointing inward with a sphere in the middle,
//                on a star stand. Your FIRST Bernal, placed in LEO (CLAUDE.md
//                "Kalpana Bernal Stack").
//   - STANFORD : two parallel torus rings on a tilted axle, on a star stand.
//                Your SECOND Bernal (CLAUDE.md "Stanford Bernal Stack - a torus
//                figure").
//
// The renders are at the SAME orthographic view as the rocket sprite (AZ 0.5 /
// EL 0.42, lean toward camera). An ANCHORED figure carries a teal colony dome
// (rule 2A5). Assets live in assets/bernal/<kind>-<colour>[-anchored].png and
// are regenerated by scripts/bernal-figures/ (see that README). The earlier
// hand-authored SVG generator was replaced by these 3D renders per the art
// sign-off (the figures must look like the published pieces).
import { assetUrl } from '../base.js';

export const BERNAL_KINDS = ['stanford', 'kalpana'];

// Seat colours we have a render for, keyed by both the colour NAME and the
// canonical seat HEX (data/crew.js), so a caller may pass either. Unknown
// colours fall back to the neutral 'bone' render.
const SEAT_HEX_NAME = {
  '#fccc00': 'gold', '#b40054': 'magenta', '#a8d8c0': 'mint',
  '#c09cc0': 'mauve', '#9c9c9c': 'gray', '#e3e0d4': 'bone',
};
const NAMES = new Set(['gold', 'magenta', 'mint', 'mauve', 'gray', 'bone']);
function colourName(colour) {
  const c = String(colour || '').trim().toLowerCase();
  if (NAMES.has(c)) return c;
  const hex = c[0] === '#' ? c : '#' + c;
  return SEAT_HEX_NAME[hex] || 'bone';
}

// Natural render size (the square PNG), so the renderer can scale like the
// rocket / freighter sprites.
const SPRITE_SIZE = 512;
export function getBernalSpriteSize() { return { width: SPRITE_SIZE, height: SPRITE_SIZE }; }

// Renderer-facing: a cached <Image> per (kind, colour, anchored). The image
// decodes async; callers must guard on `img.complete && img.naturalWidth`
// before drawing and re-render on the ready callback (set via onBernalSpriteReady).
const _imgCache = new Map();
let _readyCb = null;
export function onBernalSpriteReady(fn) { _readyCb = typeof fn === 'function' ? fn : null; }
export function getBernalSprite(colour, opts = {}) {
  const kind = opts.kind === 'kalpana' ? 'kalpana' : 'stanford';
  const name = colourName(colour);
  const anc = opts.anchored ? '-anchored' : '';
  const key = `${kind}#${name}${anc}`;
  if (_imgCache.has(key)) return _imgCache.get(key);
  const img = new Image();
  img.decoding = 'async';
  img.onload = () => { if (_readyCb) _readyCb(); };
  img.src = assetUrl(`assets/bernal/${kind}-${name}${anc}.png`);
  _imgCache.set(key, img);
  return img;
}
