#!/usr/bin/env python3
"""Generate data/rat-frontier/alpha-centauri-map.js from the pixel-art map
layers. Sites come from the PLANETS / Asteroids / star layers; each marker is
a colour blob whose hue picks a rat spectral type. Pixel coords (523x352) are
normalised to the renderer's 1400x900 world space."""
import sys, json, colorsys
sys.path.insert(0, '/tmp')
from blobs import components

SRC_W, SRC_H = 523, 352
VIEW_W, VIEW_H = 1400, 900

def hex2rgb(h):
    h=h.lstrip('#'); return tuple(int(h[i:i+2],16) for i in (0,2,4))

# Pixel hue -> rat spectral type (RAT_SPECTRAL: H/B/T/A/C).
def classify(hexc):
    r,g,b = [v/255 for v in hex2rgb(hexc)]
    h,s,v = colorsys.rgb_to_hsv(r,g,b)
    hue = h*360
    if s < 0.18:          # greyscale -> metallic
        return 'T', 'M', 'metal'
    if 20 <= hue < 70:    # yellow/tan -> cheddar/carbon
        return 'C', 'C', 'rock'
    if 70 <= hue < 170:   # green/teal -> hydrated/ice
        return 'H', 'H', 'ice'
    if 170 <= hue < 200:  # cyan -> icy/cometary
        return 'H', 'D', 'ice'
    if 200 <= hue < 260:  # blue -> brie/basaltic
        return 'B', 'B', 'rock'
    if 260 <= hue < 320:  # magenta/purple -> aged/volcanic
        return 'A', 'V', 'volcanic'
    return 'A', 'A', 'volcanic'   # red

def nx(cx): return round(cx/SRC_W*VIEW_W, 1)
def ny(cy): return round(cy/SRC_H*VIEW_H, 1)

sites = []

# --- Stars (zone centres / home anchors) ---
star_names = ['Centauri A', 'Centauri B', 'Proxima Centauri']
_,_,stars = components('/tmp/aclayers/L3_Layer 1.png', min_px=40)
stars.sort(key=lambda b:-b['n'])
for i,b in enumerate(stars):
    sites.append({
        'id': f'ac_star_{i+1}', 'name': star_names[i] if i<len(star_names) else f'Star {i+1}',
        'body': star_names[i] if i<len(star_names) else f'Star {i+1}',
        'type': 'star', 'cls': 'star', 'spectralType': 'C',
        'x': nx(b['cx']), 'y': ny(b['cy']), 'hydration': 0, 'vps': 0,
        'isStar': True, 'srcColor': b['color'], 'srcPx': [b['cx'], b['cy']], 'srcN': b['n'],
    })

# --- Planets / major sites ---
_,_,planets = components('/tmp/aclayers/L4_PLANETS.png', min_px=20)
planets.sort(key=lambda b:-b['n'])
for i,b in enumerate(planets):
    sp,cls,kind = classify(b['color'])
    big = b['n'] >= 250
    sites.append({
        'id': f'ac_planet_{i+1}', 'name': f'AC-{i+1:02d}',
        'body': f'AC-{i+1:02d}', 'type': 'planet' if big else 'moon',
        'cls': cls, 'spectralType': sp, 'kind': kind,
        'x': nx(b['cx']), 'y': ny(b['cy']),
        'hydration': {'H':4,'D':3,'B':2,'C':1,'A':1,'M':0}.get(cls,1),
        'vps': 3 if big else 1, 'r_px': max(b['w'],b['h']),
        'srcColor': b['color'], 'srcPx': [b['cx'], b['cy']], 'srcN': b['n'],
    })

# --- Asteroid field (keep the more substantial ones) ---
_,_,roids = components('/tmp/aclayers/L5_Asteroids.png', min_px=8)
roids.sort(key=lambda b:-b['n'])
for i,b in enumerate(roids):
    sp,cls,kind = classify(b['color'])
    sites.append({
        'id': f'ac_roid_{i+1}', 'name': f'Belt {i+1:03d}',
        'body': f'Belt {i+1:03d}', 'type': 'asteroid',
        'cls': cls, 'spectralType': sp, 'kind': kind,
        'x': nx(b['cx']), 'y': ny(b['cy']),
        'hydration': {'H':3,'D':2,'B':1,'C':1,'A':0,'M':0}.get(cls,0),
        'vps': 1, 'srcColor': b['color'], 'srcPx': [b['cx'], b['cy']], 'srcN': b['n'],
    })

out = {
    'meta': {'src': 'alpha_centari.aseprite', 'srcSize': [SRC_W,SRC_H],
             'view': [VIEW_W,VIEW_H], 'stars': len(stars),
             'planets': len(planets), 'asteroids': len(roids)},
    'sites': sites,
}
js = "// AUTO-GENERATED by scripts/gen-alpha-centauri-map.py from the\n" \
     "// alpha_centari.aseprite pixel-art layers (PLANETS / Asteroids / stars).\n" \
     "// Each site is a colour blob; hue picks the rat spectral type. Pixel\n" \
     "// coords are normalised to the renderer's 1400x900 world space. Names\n" \
     "// are placeholders pending a proper gazetteer pass.\n\n" \
     "export const ALPHA_CENTAURI_MAP = " + json.dumps(out, indent=2) + ";\n\n" \
     "export const ALPHA_CENTAURI_SITES = ALPHA_CENTAURI_MAP.sites;\n"
open('/home/user/high-frontier-fan-game/data/rat-frontier/alpha-centauri-map.js','w').write(js)
print(f"stars={len(stars)} planets={len(planets)} asteroids={len(roids)} total={len(sites)}")
