#!/usr/bin/env python3
"""Build the Alpha Centauri movement graph. Curved Hohmann routes on the
'nodes' layer are hard to trace pixel-perfect, so the navigable graph is a
k-nearest-neighbour network over the sites (guaranteed connected via an MST
pass), with each edge annotated by the route-mask fraction it overlaps -
high `frac` means the edge follows an actually-drawn line. Provisional."""
import json, math
from PIL import Image

MAPJS = '/home/user/high-frontier-fan-game/data/rat-frontier/alpha-centauri-map.js'
NODES = '/tmp/aclayers/L6_nodes.png'
K = 3

def load():
    js = open(MAPJS).read()
    data = json.loads(js[js.index('{'):js.rindex('};')+1])
    return data, data['sites']

def route_mask(path, dilate=2):
    im = Image.open(path).convert('RGBA'); W,H = im.size; px = im.load()
    def is_route(p):
        if p[3] < 60: return False
        r,g,b,_ = p
        return r > 90 and r-b > 25 and g < 170
    base = [[is_route(px[x,y]) for x in range(W)] for y in range(H)]
    m = [[False]*W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            if base[y][x]:
                for dy in range(-dilate,dilate+1):
                    for dx in range(-dilate,dilate+1):
                        ny,nx=y+dy,x+dx
                        if 0<=ny<H and 0<=nx<W: m[ny][nx]=True
    return m,W,H

def seg_frac(x0,y0,x1,y1,mask,W,H):
    n=int(max(abs(x1-x0),abs(y1-y0)))+1
    if n<2: return 1.0
    hit=0
    for i in range(n+1):
        t=i/n; x=int(round(x0+(x1-x0)*t)); y=int(round(y0+(y1-y0)*t))
        if 0<=x<W and 0<=y<H and mask[y][x]: hit+=1
    return hit/(n+1)

def main():
    data,sites=load()
    mask,W,H=route_mask(NODES)
    pts=[(s['srcPx'][0],s['srcPx'][1],s) for s in sites]
    adj={}   # id -> set(id)
    def link(a,b):
        adj.setdefault(a,set()).add(b); adj.setdefault(b,set()).add(a)
    # kNN
    for i,(x0,y0,si) in enumerate(pts):
        ds=sorted(((math.hypot(x1-x0,y1-y0),j) for j,(x1,y1,sj) in enumerate(pts) if j!=i))
        for d,j in ds[:K]:
            link(si['id'],pts[j][2]['id'])
    # MST pass to guarantee one connected component (Prim over full graph)
    idx={s['id']:k for k,s in enumerate(sites)}
    import heapq
    intree=set([sites[0]['id']]); pq=[]
    def push(a):
        xa,ya,_=pts[idx[a]]
        for j,(xb,yb,sb) in enumerate(pts):
            if sb['id'] in intree: continue
            heapq.heappush(pq,(math.hypot(xb-xa,yb-ya),a,sb['id']))
    push(sites[0]['id'])
    while len(intree)<len(sites):
        if not pq: break
        d,a,b=heapq.heappop(pq)
        if b in intree: continue
        link(a,b); intree.add(b); push(b)
    # emit edges with route-confidence
    edges=[]; seen=set()
    for a,nbrs in adj.items():
        xa,ya,_=pts[idx[a]]
        for b in nbrs:
            key=tuple(sorted((a,b)))
            if key in seen: continue
            seen.add(key)
            xb,yb,_=pts[idx[b]]
            d=math.hypot(xb-xa,yb-ya)
            edges.append({'a':a,'b':b,'dv':round(d/W*1400,1),
                          'frac':round(seg_frac(xa,ya,xb,yb,mask,W,H),2)})
    deg={}
    for e in edges:
        deg[e['a']]=deg.get(e['a'],0)+1; deg[e['b']]=deg.get(e['b'],0)+1
    isolated=[s['id'] for s in sites if deg.get(s['id'],0)==0]
    drawn=sum(1 for e in edges if e['frac']>=0.5)
    data['edges']=edges
    data['meta']['edges']=len(edges)
    data['meta']['edgesOnDrawnRoute']=drawn
    data['meta']['isolatedSites']=len(isolated)
    js="// AUTO-GENERATED by scripts/gen-alpha-centauri-map.py +\n" \
       "// scripts/gen-alpha-centauri-edges.py from alpha_centari.aseprite.\n" \
       "// sites: colour blobs (hue -> rat spectral type). edges: a kNN+MST\n" \
       "// movement graph over the sites, each annotated with `frac` = how much\n" \
       "// of the edge overlaps a drawn route-line ('nodes' layer). frac>=0.5\n" \
       "// means it follows an actual drawn route. PROVISIONAL adjacency:\n" \
       "// curved Hohmann arcs are not yet traced pixel-exact. Coords are\n" \
       "// normalised to the renderer's 1400x900 world space.\n\n" \
       "export const ALPHA_CENTAURI_MAP = "+json.dumps(data,indent=2)+";\n\n" \
       "export const ALPHA_CENTAURI_SITES = ALPHA_CENTAURI_MAP.sites;\n" \
       "export const ALPHA_CENTAURI_EDGES = ALPHA_CENTAURI_MAP.edges;\n"
    open(MAPJS,'w').write(js)
    print(f"edges={len(edges)} on_drawn_route={drawn} isolated={len(isolated)} sites={len(sites)}")

if __name__=='__main__':
    main()
